apiVersion: v2
name: meta
description: Berserk Meta Service - Metadata management
type: application
version: 1.0.49
appVersion: 1.0.49
dependencies:
  - name: berserk-common
    version: "*"
    repository: "file://../berserk-common"
