{{- if eq (.Values.library.storage | default "emptyDir") "pvc" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-library" (include "berserk-common.fullname" .) }}
  labels:
    {{- include "berserk-common.labels" . | nindent 4 }}
spec:
  accessModes: [ "ReadWriteOnce" ]
  {{- with .Values.library.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.library.storageSize | default "1Gi" }}
{{- end }}
