{{- if and .Values.library.gitRepo .Values.library.gitToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-library-git" (include "berserk-common.fullname" .) }}
  labels:
    {{- include "berserk-common.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.library.gitToken | quote }}
{{- end }}
