{{- if and .Values.library.gitRepo .Values.library.ssh.managed }}
{{- $existing := lookup "v1" "Secret" .Release.Namespace .Values.library.ssh.secretName }}
{{- if or (and .Values.library.ssh.privateKey .Values.library.ssh.knownHosts) $existing }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.library.ssh.secretName }}
  labels:
    {{- include "berserk-common.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if and .Values.library.ssh.privateKey .Values.library.ssh.knownHosts }}
  id_ed25519: {{ .Values.library.ssh.privateKey | b64enc | quote }}
  known_hosts: {{ .Values.library.ssh.knownHosts | b64enc | quote }}
  {{- else }}
  id_ed25519: {{ index $existing.data "id_ed25519" }}
  known_hosts: {{ index $existing.data "known_hosts" }}
  {{- end }}
{{- end }}
{{- end }}
