{{- if ne (.Values.config.k8sAttributes.passthrough | toString) "true" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "berserk-common.fullname" . }}
  labels:
    {{- include "berserk-common.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "berserk-common.fullname" . }}-{{ .Release.Namespace }}
  labels:
    {{- include "berserk-common.labels" . | nindent 4 }}
rules:
  # For k8sattributes processor
  - apiGroups: [""]
    resources:
      - pods
      - namespaces
      - nodes
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources:
      - replicasets
      - deployments
      - daemonsets
      - statefulsets
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "berserk-common.fullname" . }}-{{ .Release.Namespace }}
  labels:
    {{- include "berserk-common.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "berserk-common.fullname" . }}-{{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ include "berserk-common.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
