{{- if .Values.config.ingestToken.create }}
{{- $existing := lookup "v1" "Secret" .Release.Namespace .Values.config.ingestToken.secretName }}
{{- if or .Values.config.ingestToken.value $existing }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.config.ingestToken.secretName }}
  labels:
    {{- include "berserk-common.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.config.ingestToken.value }}
  {{ .Values.config.ingestToken.key }}: {{ .Values.config.ingestToken.value | b64enc | quote }}
  {{- else }}
  {{ .Values.config.ingestToken.key }}: {{ index $existing.data .Values.config.ingestToken.key }}
  {{- end }}
{{- end }}
{{- end }}
