{{- if and .Values.config.ingestToken.create .Values.config.ingestToken.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.config.ingestToken.secretName }}
  labels:
    {{- include "berserk-common.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.config.ingestToken.key }}: {{ .Values.config.ingestToken.value | b64enc | quote }}
{{- end }}
