{{ include "berserk-common.configmap.metadata" . }}
data:
  config.yaml: |
    bind: "0.0.0.0:9502"
    meta_endpoint: {{ .Values.config.metaEndpoint | quote }}
    query_endpoint: {{ .Values.config.queryEndpoint | quote }}
    cloud_storage_access_key: ${JANITOR_STORAGE_ACCESS_KEY:}
    cloud_storage_secret_key: ${JANITOR_STORAGE_SECRET_KEY:}
    cache_dir: {{ .Values.config.cacheDir | quote }}
    merger_interval_seconds: {{ .Values.config.mergerIntervalSeconds }}
    max_segments_per_batch: {{ .Values.config.maxSegmentsPerBatch }}
    min_segments: {{ .Values.config.minSegments }}
    max_segment_age_days: {{ .Values.config.maxSegmentAgeDays }}
    {{- if .Values.config.targetDatasets }}
    target_datasets: {{ .Values.config.targetDatasets | toJson }}
    {{- else }}
    target_datasets: []
    {{- end }}
    {{- include "berserk-common.observability-config" . | nindent 4 }}
    {{- $defaultDataset := .Values.global.defaultDataset | default "default" }}
    probe_jobs:
      - name: "default_take_one"
        query: "{{ $defaultDataset }} | take 1"
        interval_seconds: 60
        since: "1h ago"
