{{- define "janitor.config-data" -}}
data:
  config.yaml: |
    bind: "0.0.0.0:9502"
    meta_endpoint: {{ .Values.config.metaEndpoint | quote }}
    query_endpoint: {{ .Values.config.queryEndpoint | quote }}
    cloud_storage_access_key: ${JANITOR_STORAGE_ACCESS_KEY:}
    cloud_storage_secret_key: ${JANITOR_STORAGE_SECRET_KEY:}
    cache_dir: {{ .Values.config.cacheDir | quote }}
    merger_interval_seconds: {{ .Values.config.mergerIntervalSeconds }}
    shutdown_grace_seconds: {{ .Values.terminationGracePeriodSeconds }}
    max_segments_per_batch: {{ .Values.config.maxSegmentsPerBatch }}
    min_segments: {{ .Values.config.minSegments }}
    max_segment_age_days: {{ .Values.config.maxSegmentAgeDays }}
    {{- if .Values.config.targetTables }}
    target_tables: {{ .Values.config.targetTables | toJson }}
    {{- else }}
    target_tables: []
    {{- end }}
    {{- include "berserk-common.observability-config" . | nindent 4 }}
    {{- if .Values.config.probeJobs }}
    probe_jobs:
      {{- toYaml .Values.config.probeJobs | nindent 6 }}
    {{- else }}
    probe_jobs: []
    {{- end }}
{{- end }}
{{- include "berserk-common.configmap" . }}
