apiVersion: v2
name: admin-ui
description: Berserk UI
type: application
version: 1.0.118
appVersion: 1.0.118
dependencies:
  - name: berserk-common
    version: "*"
    repository: "file://../berserk-common"
