{{ include "berserk-common.configmap.metadata" . }}
data:
  config.yaml: |
    bind: "0.0.0.0:{{ .Values.service.port }}"
    meta_endpoint: {{ .Values.config.metaEndpoint | quote }}
    cloud_storage_access_key: ${AWS_ACCESS_KEY_ID:}
    cloud_storage_secret_key: ${AWS_SECRET_ACCESS_KEY:}
    max_concurrent_queries: {{ .Values.config.maxConcurrentQueries }}
    {{- if hasKey .Values.config "workersPerQuery" }}
    workers_per_query: {{ .Values.config.workersPerQuery }}
    {{- end }}

    {{- if .Values.cache.enabled }}
    cache:
      dir: "/segment_cache"
      total_size_limit: "{{ .Values.cache.size }}"
    {{- end }}
    {{- include "berserk-common.observability-config" . | nindent 4 }}
