{{- if .Values.global.s3Credentials.managed }}
{{- $existing := lookup "v1" "Secret" .Release.Namespace .Values.global.s3Credentials.secretName }}
{{- if or (and .Values.global.s3Credentials.accessKeyId .Values.global.s3Credentials.secretAccessKey) $existing }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.s3Credentials.secretName }}
  labels:
    {{- include "berserk.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if and .Values.global.s3Credentials.accessKeyId .Values.global.s3Credentials.secretAccessKey }}
  {{ .Values.global.s3Credentials.accessKeyIdKey }}: {{ .Values.global.s3Credentials.accessKeyId | b64enc | quote }}
  {{ .Values.global.s3Credentials.secretAccessKeyKey }}: {{ .Values.global.s3Credentials.secretAccessKey | b64enc | quote }}
  {{- else }}
  {{ .Values.global.s3Credentials.accessKeyIdKey }}: {{ index $existing.data .Values.global.s3Credentials.accessKeyIdKey }}
  {{ .Values.global.s3Credentials.secretAccessKeyKey }}: {{ index $existing.data .Values.global.s3Credentials.secretAccessKeyKey }}
  {{- end }}
{{- end }}
{{- end }}
{{- if .Values.global.postgresCredentials.managed }}
{{- $existing := lookup "v1" "Secret" .Release.Namespace .Values.global.postgresCredentials.secretName }}
{{- if or .Values.global.postgresCredentials.databaseUrl $existing }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.postgresCredentials.secretName }}
  labels:
    {{- include "berserk.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.global.postgresCredentials.databaseUrl }}
  {{ .Values.global.postgresCredentials.databaseUrlKey }}: {{ .Values.global.postgresCredentials.databaseUrl | b64enc | quote }}
  {{- else }}
  {{ .Values.global.postgresCredentials.databaseUrlKey }}: {{ index $existing.data .Values.global.postgresCredentials.databaseUrlKey }}
  {{- end }}
{{- end }}
{{- end }}
{{- if .Values.global.imageCredentials.managed }}
{{- $existing := lookup "v1" "Secret" .Release.Namespace "ghcr-credentials" }}
{{- if or .Values.global.imageCredentials.password $existing }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-credentials
  labels:
    {{- include "berserk.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  {{- if .Values.global.imageCredentials.password }}
  .dockerconfigjson: {{ printf `{"auths":{"%s":{"username":"%s","password":"%s","auth":"%s"}}}` .Values.global.imageCredentials.registry "jakobgt" .Values.global.imageCredentials.password (printf "%s:%s" "jakobgt" .Values.global.imageCredentials.password | b64enc) | b64enc | quote }}
  {{- else }}
  .dockerconfigjson: {{ index $existing.data ".dockerconfigjson" }}
  {{- end }}
{{- end }}
{{- end }}
