{{- if .Values.global.s3Credentials.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.s3Credentials.secretName }}
  labels:
    {{- include "berserk.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.global.s3Credentials.accessKeyIdKey }}: {{ .Values.global.s3Credentials.accessKeyId | b64enc | quote }}
  {{ .Values.global.s3Credentials.secretAccessKeyKey }}: {{ .Values.global.s3Credentials.secretAccessKey | b64enc | quote }}
{{- end }}
{{- if .Values.global.postgresCredentials.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.postgresCredentials.secretName }}
  labels:
    {{- include "berserk.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.global.postgresCredentials.databaseUrlKey }}: {{ .Values.global.postgresCredentials.databaseUrl | b64enc | quote }}
{{- end }}
{{- if .Values.global.imageCredentials.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-credentials
  labels:
    {{- include "berserk.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf `{"auths":{"%s":{"username":"%s","password":"%s","auth":"%s"}}}` .Values.global.imageCredentials.registry .Values.global.imageCredentials.username .Values.global.imageCredentials.password (printf "%s:%s" .Values.global.imageCredentials.username .Values.global.imageCredentials.password | b64enc) | b64enc | quote }}
{{- end }}
