apiVersion: v2
name: permissions
description: Berserk permissions service (authorization tuples + /v1/check)
type: application
version: 1.0.152-rc.9
appVersion: 1.0.152-rc.9
dependencies:
  - name: berserk-common
    version: "*"
    repository: "file://../berserk-common"
