apiVersion: v2
name: ui
description: Berserk UI - Web interface for query and visualization
type: application
version: 1.1.1-rc.7
appVersion: 1.1.1-rc.7
dependencies:
  - name: berserk-common
    version: "*"
    repository: "file://../berserk-common"
