apiVersion: v2
name: ingest
description: Berserk Ingest Service - OTLP HTTP/gRPC ingest collector
type: application
version: 1.1.1-rc.8
appVersion: 1.1.1-rc.8
dependencies:
  - name: berserk-common
    version: "*"
    repository: "file://../berserk-common"
