apiVersion: v2
name: ingest
description: Berserk Ingest Service - OTLP HTTP/gRPC ingest collector
type: application
version: 1.1.2-rc.5
appVersion: 1.1.2-rc.5
dependencies:
  - name: berserk-common
    version: "*"
    repository: "file://../berserk-common"
