{{- define "nursery.config-data" -}}
data:
  config.yaml: |
    http_bind: "0.0.0.0:{{ .Values.service.port }}"
    meta_endpoint: {{ .Values.config.metaEndpoint | quote }}
    cloud_storage_access_key: ${NURSERY_STORAGE_ACCESS_KEY:}
    cloud_storage_secret_key: ${NURSERY_STORAGE_SECRET_KEY:}
    working_dir: "/var/cache/nursery"
    meta_default_poll_interval_secs: {{ .Values.config.metaPollIntervalSecs }}
    stream_timeout_secs: {{ .Values.config.streamTimeoutSecs }}
    {{- if hasKey .Values.config "forceMergeStaleThresholdSecs" }}
    force_merge_stale_threshold_secs: {{ .Values.config.forceMergeStaleThresholdSecs }}
    {{- end }}
    {{- if .Values.config.queryGrpcBind }}
    query_grpc_bind: {{ .Values.config.queryGrpcBind | quote }}
    qws_bin: "/qws_bin"
    {{- end }}
    {{- include "berserk-common.observability-config" . | nindent 4 }}
{{- end }}
{{- include "berserk-common.configmap" . }}
